version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: maillens-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: maillens
      POSTGRES_PASSWORD: maillens
      POSTGRES_DB: maillens
    ports:
    - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data


  redis:
    image: redis:7-alpine
    container_name: maillens-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata: